# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    client_manager:
        class: AppBundle\Services\ManagerClient
        arguments: ["%x-redmine-api-key%"]

    custom_pagination:
        class: AppBundle\Services\Pagination
        arguments: ["@client_manager"]