# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    client_manager:
        class: AppBundle\Services\ManagerClient
        arguments: ["%x-redmine-api-key%"]

    time_entry_manager:
        class: AppBundle\Services\TimeEntryManager
        arguments: ["@client_manager", "@form.factory", "@router", "@session"]

    custom_pagination:
        class: AppBundle\Services\Pagination
        arguments: ["@client_manager"]